import type { ThoughtAction } from "@/lib/types";

export const mockExpansionNodes: Record<ThoughtAction, { text: string; kind: "idea" | "question" | "insight" | "risk" | "challenge" }[]> = {
  expand: [
    { text: "谁会最频繁地遇到这个问题？", kind: "question" },
    { text: "目前人们怎么解决它？", kind: "question" },
    { text: "AI 在这里能带来什么独特价值？", kind: "question" },
    { text: "最小可验证的产品是什么？", kind: "idea" },
    { text: "用户真正想完成的结果是什么？", kind: "question" },
    { text: "最先需要验证的关键假设是什么？", kind: "question" },
    { text: "这个方向和现有方案差在哪里？", kind: "question" },
    { text: "哪些条件会改变问题的重要性？", kind: "question" },
  ],
  deep: [
    { text: "这个问题通常在什么情境下发生？", kind: "question" },
    { text: "最让人困扰的具体环节是什么？", kind: "question" },
    { text: "现有替代方案为什么不够好？", kind: "question" },
    { text: "怎样验证它真的重要？", kind: "question" },
    { text: "问题发生前后分别出现了什么？", kind: "question" },
    { text: "哪些前提成立时这个判断才正确？", kind: "question" },
    { text: "如何观察到问题正在改善？", kind: "question" },
    { text: "有没有更小的例子能说明原因？", kind: "question" },
  ],
  challenge: [
    { text: "用户为什么不直接用现有工具？", kind: "challenge" },
    { text: "这个需求是否足够高频？", kind: "challenge" },
    { text: "去掉 AI 后，核心价值还成立吗？", kind: "challenge" },
    { text: "什么证据会证明这个假设是错的？", kind: "challenge" },
    { text: "哪些用户其实并不需要这个方案？", kind: "challenge" },
    { text: "这个结论是否把相关性当成因果？", kind: "challenge" },
    { text: "有没有反例能推翻当前判断？", kind: "challenge" },
    { text: "如果关键假设不成立，方案还成立吗？", kind: "challenge" },
  ],
  risk: [
    { text: "用户是否愿意持续为它付费？", kind: "risk" },
    { text: "推理成本会不会高于单用户收入？", kind: "risk" },
    { text: "关键数据是否能安全获得和处理？", kind: "risk" },
    { text: "成熟平台能否快速复制这个功能？", kind: "risk" },
    { text: "用户在哪一步最可能放弃？", kind: "risk" },
    { text: "哪些依赖一旦失效会阻断交付？", kind: "risk" },
    { text: "规模扩大后成本会怎样变化？", kind: "risk" },
    { text: "误判需求会造成什么实际损失？", kind: "risk" },
  ],
  perspective: [
    { text: "从第一次使用的用户角度看，哪里会困惑？", kind: "question" },
    { text: "从投资人的角度，增长空间在哪里？", kind: "question" },
    { text: "从工程师角度，最难验证的部分是什么？", kind: "question" },
    { text: "三年后，这个问题会变得更重要吗？", kind: "question" },
    { text: "从首次使用者角度，哪里最难理解？", kind: "question" },
    { text: "从维护者角度，长期成本在哪里？", kind: "question" },
    { text: "从反对者角度，最有力的质疑是什么？", kind: "challenge" },
    { text: "从受影响但不付费的人看，价值是什么？", kind: "question" },
  ],
};
